CG.ProgDec.UI/Controllers/DeclarationController.cs
using CG.ProgDec.BL;
using CG.ProgDec.BL.Models;
using Microsoft.AspNetCore.Mvc;

namespace CG.ProgDec.UI.Controllers
{
    public class DeclarationController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Title = "List of Declarations";
            return View(DeclarationManager.Load());
        }

        // Filter the Declaration by ProgramId
        public IActionResult Browse(int id)
        {
            var results = ProgramManager.LoadById(id);
            ViewBag.Title = "List of  " + results.Description + "  Declaration";                  // -- MODIFY LATER
            return View(nameof(Index), DeclarationManager.Load(id));
        }

        public IActionResult Details(int id)
        {
            var item = DeclarationManager.LoadById(id);
            ViewBag.Title = "Details";
            return View(DeclarationManager.LoadById(id));
        }

        public IActionResult Create()
        {
            ViewBag.Title = "Create";
            return View();
        }

        [HttpPost]
        public IActionResult Create(Declaration declaration)
        {
            try
            {
                int result = DeclarationManager.Insert(declaration);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                throw;
            }
        }


        public IActionResult Edit(int id)   
        {
            var item = DeclarationManager.LoadById(id);
            ViewBag.Title = "Edit";
            return View(item);
        }

        [HttpPost]
        public IActionResult Edit(int id, Declaration declaration, bool rollback = false)
        {
            try
            {
                int result = DeclarationManager.Update(declaration, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message; // ViewBag <-- Special bag where we can put anything we want. 
                return View(declaration);
            }
        }

        public IActionResult Delete(int id)
        {
            var item = DeclarationManager.LoadById(id);
            ViewBag.Title = "Delete";
            return View(item);
        }

        [HttpPost]
        public IActionResult Delete(int id, Declaration declaration, bool rollback = false)
        {
            try
            {
                int result = DeclarationManager.Delete(id, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(declaration);
            }
        }

    }
}

CG.ProgDec.UI/Controllers/DegreeTypeController.cs
using CG.ProgDec.BL;
using CG.ProgDec.BL.Models;
using Microsoft.AspNetCore.Mvc;

namespace CG.ProgDec.UI.Controllers
{
    public class DegreeTypeController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Title = "List of Degree Types";
            return View(DegreeTypeManager.Load());
        }

        public IActionResult Details(int id)
        {
            var item = DegreeTypeManager.LoadById(id);
            ViewBag.Title = "Details for " + item.Description;
            return View(item);
        }

        public IActionResult Create()
        {
            ViewBag.Title = "Create a Degree Type";
            return View();
        }

        [HttpPost]
        public IActionResult Create(DegreeType degreeType)
        {
            try
            {
                int result = DegreeTypeManager.Insert(degreeType);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Title = "Create a Degree Type";
                ViewBag.Error = ex.Message;
                return View(degreeType);
            }
        }

        public IActionResult Edit(int id)
        {
            var item = DegreeTypeManager.LoadById(id);
            ViewBag.Title = "Edit " + item.Description;
            return View(item);
        }

        [HttpPost]
        public IActionResult Edit(int id, DegreeType degreeType, bool rollback = false)
        {
            try
            {
                int result = DegreeTypeManager.Update(degreeType, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Title = "Edit " + degreeType.Description;
                ViewBag.Error = ex.Message;
                return View(degreeType);
            }
        }

        public IActionResult Delete(int id)
        {
            var item = DegreeTypeManager.LoadById(id);
            ViewBag.Title = "Delete " + item.Description;
            return View(item);
        }

        [HttpPost]
        public IActionResult Delete(int id, DegreeType degreeType, bool rollback = false)
        {
            try
            {
                int result = DegreeTypeManager.Delete(id, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Title = "Delete " + degreeType.Description;
                ViewBag.Error = ex.Message;
                return View(degreeType);
            }
        }


    }
}

CG.ProgDec.UI/Controllers/StudentController.cs
using CG.ProgDec.BL;
using CG.ProgDec.BL.Models;
using CG.ProgDec.PL;
using CG.ProgDec.UI.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CG.ProgDec.UI.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.Title = "List of Students";
            return View(StudentManager.Load());
        }

        public IActionResult Details(int id)
        {
            var item = StudentManager.LoadById(id);
            ViewBag.Title = "Details for " + item.FullName;
            return View(item);
        }

        public IActionResult Create()
        {

            ViewBag.Title = "Create a Student";
            return View();
        }

        [HttpPost]
        public IActionResult Create(Student student)
        {
            try
            {
                int result = StudentManager.Insert(student);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Title = "Create a Student";
                ViewBag.Error = ex.Message;
                return View(student);
            }
        }

        public IActionResult Edit(int id)
        {

            StudentVM studentVM = new StudentVM(id);
            ViewBag.Title = "Edit " + studentVM.Student.FullName;
            HttpContext.Session.SetObject("advisorids", studentVM.AdvisorIds);
            return View(studentVM);
        }

        [HttpPost]
        public IActionResult Edit(int id, StudentVM studentVM, bool rollback = false)
        {
            try
            {
                IEnumerable<int> newAdvisorIds = new List<int>();
                if(studentVM.AdvisorIds != null)
                {
                    newAdvisorIds = studentVM.AdvisorIds;
                }

                IEnumerable<int> oldAdvisorIds = new List<int>();
                oldAdvisorIds = GetObject();

                IEnumerable<int> deletes = oldAdvisorIds.Except(newAdvisorIds);
                IEnumerable<int> adds = newAdvisorIds.Except(newAdvisorIds);

                deletes.ToList().ForEach(d => StudentAdvisorManager.Delete(id, d));
                adds.ToList().ForEach(d => StudentAdvisorManager.Delete(id, d));

                int result = StudentManager.Update(studentVM.Student, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                ViewBag.Title = "Edit " + studentVM.Student.FullName;
                ViewBag.Error = ex.Message;
                return View(studentVM);
            }
        }

        public IEnumerable<int> GetObject()
        {
            if (HttpContext.Session.GetObject<IEnumerable<int>>("advisorids") != null)
            {
                return HttpContext.Session.GetObject<IEnumerable<int>>("advisorids");
            }
            else
            {
                return null;
            }
        }

        public IActionResult Delete(int id)
        {
            var item = StudentManager.LoadById(id);
            ViewBag.Title = "Delete " + item.FullName;
            return View(item);
        }

        [HttpPost]
        public IActionResult Delete(int id, Student student, bool rollback = false)
        {
            try
            {
                int result = StudentManager.Delete(id, rollback);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(student);
            }
        }


    }
}

CG.ProgDec.UI/Views/Shared/_AdvisorPartial.cshtml
@model IEnumerable<CG.ProgDec.BL.Models.Advisor>

<div>
    <table id="students" class="table data-table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)

                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id=item.Id}) |
                        @Html.ActionLink("Details", "Details", new { id=item.Id}) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.Id})
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script type="text/javascript" class="init">
    $.noConflict();
    jQuery(document).ready(function ($) {
        $('#myData').DataTable({
            "lengthMenu": [[5, 10, 25, 30, -1], [5, 10, 25, 30, "All"]]
        });
    }); 
</script>

CG.ProgDec.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Declarations</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CG.ProgDec.UI.styles.css" asp-append-version="true" />

    <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark text-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Declarations</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="DegreeType" asp-action="Index">Degree Types</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Program" asp-action="Index">Programs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Declaration" asp-action="Index">Declarations</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            @{
                                CG.ProgDec.BL.UserManager.Seed();
                                var fullname = HttpContextAccessor.HttpContext?.Session.GetString("fullname");
                                if (fullname != null) fullname = fullname.Replace("\"", "");
                            }
                            <a class="nav-link text-light">@fullname</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2 sidebar rounded-top">
                <div class="header rounded-top p-2">
                    <h4>Programs</h4>
                </div>
                <div>
                    @await Component.InvokeAsync("Sidebar")
                </div>

                <div class="header p-1">
                    <h4>Shopping Cart</h4>
                </div>
                <div>
                    @await Component.InvokeAsync("ShoppingCartComponent")
                </div>

            </div>

            <div id="overlay" onclick="off()">
                <div id="imageproplarge">
                    <img class="imageproplarge" id="output" />
                </div>
            </div>

            <div class="col-md-9 main body-content rounded-top">
                <div class="header rounded-top p-2">
                    <h4>@ViewBag.Title</h4>
                </div>
                <main role="main" class="pb-3">
                    <div class="text-danger m-2">@ViewBag.Error</div>
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CG.ProgDec.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>


<script type="text/javascript">
    function off() {
        console.log('Off');
        document.getElementById("overlay").style.display = "none";
    }
    function on(picture) {
        console.log('On');
        document.getElementById("overlay").style.display = "block";
        document.getElementById("output").src = picture;
    }
</script>

<script type="text/javascript">
    function AddToCart(id) {
        $.get("/ShoppingCart/Add/" + id, function (data) {
            var cartcount = parseInt($("#cartcount").val()) + 1;
            $("#cartcount").val(cartcount);
            $("#cartcountdisp").text(cartcount + " items");
        });
    }
</script>